"""document url column

Revision ID: 7f534b6c672d
Revises: 3cd85d086fdf
Create Date: 2026-07-07 23:10:54.950730
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f534b6c672d'
down_revision: Union[str, None] = '3cd85d086fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
