"""document sop fields

Revision ID: 848eaac5682b
Revises: 7f534b6c672d
Create Date: 2026-07-08 00:03:47.441568
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '848eaac5682b'
down_revision: Union[str, None] = '7f534b6c672d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: the models declare Python-side
    # defaults, which SQLAlchemy applies on INSERT only and never emits as DDL.
    # On Postgres, ADD COLUMN ... NOT NULL without a default fails outright on a
    # table that already has rows, and the Dockerfile runs `alembic upgrade head`
    # on every container start. SQLite's batch mode rebuilds the table, which
    # masked this until the first real Postgres deploy.
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30),
                                      nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('editor', sa.String(length=200),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('published_for', sa.String(length=200),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('co_authors', sa.String(length=500),
                                      nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('co_authors')
        batch_op.drop_column('published_for')
        batch_op.drop_column('editor')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
