"""document sop fields

Revision ID: 848eaac5682b
Revises: 7f534b6c672d
Create Date: 2026-07-08 00:03:47.441568
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '848eaac5682b'
down_revision: Union[str, None] = '7f534b6c672d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('editor', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('published_for', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('co_authors', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('co_authors')
        batch_op.drop_column('published_for')
        batch_op.drop_column('editor')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
